<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Suresh_D" failures="1" tests="3" name="Surefire test" time="9.107" errors="0" timestamp="2025-06-17T11:10:03 BST">
  <testcase classname="contactmanagementsystem.com.sudha.tests.LoginTest" name="openSignupPage" time="1.757"/>
  <testcase classname="contactmanagementsystem.com.sudha.tests.LoginTest" name="validateHeaderText" time="1.033"/>
  <testcase classname="contactmanagementsystem.com.sudha.tests.SignUpTest" name="validSignUp" time="1.28">
    <failure type="java.lang.AssertionError" message="expected [Contact List] but found [Add User]">
      <![CDATA[java.lang.AssertionError: expected [Contact List] but found [Add User]
at contactmanagementsystem.com.sudha.tests.SignUpTest.validSignUp(SignUpTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- validSignUp -->
  <testcase classname="contactmanagementsystem.com.sudha.base.BaseTest" name="@BeforeSuite cleanReports" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite cleanReports -->
  <testcase classname="contactmanagementsystem.com.sudha.base.BaseTest" name="@BeforeSuite cleanReports" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite cleanReports -->
</testsuite> <!-- Surefire test -->
